### ISSUE TITLE
how to reset credentials ? 

### ISSUE THREAD

**Issue by rocky-III** [thunderbird/webdav-filelink#11]
how to reset credentials for a dav account in Thunderbird? Where are the credentials stored?
Can you name me the file  in the .thunderbird folder?  Thanks

**Comment by jobisoft** [comment]
Credentials are stored in the password manager of Thunderbird. Go to Tools -> Settings and search for "passwords". The view should reduce and show a "Saved Passwords" button. That opens the password manager.

**Comment by rocky-III** [comment]
thanks that helped
