### ISSUE TITLE
FileLink provider for WebDav

### ISSUE THREAD

**Issue by hidriveuser** [thunderbird/webdav-filelink#3]
I am using Thunderbird 78.10,  32 bit, with Windows 7 with FileLink Provider for WebDav, trying to get it to send large email attachments to my IONOS HiDrive account which has a WebDav a/c set up, and include a link in the emails instead. I have tried using the HiDrive recommended webdav urls for setting up the addon and a lot of variations but always get the error message "unable to upload...." and I never get asked for a username or password by the addon in Thunderbird. The urls do work when used via a browser but never in a Thunderbird email.
HiDrive says I should enter webdav.hidrive.ionos.com  using port 443, for private url and hidrive.ionos.com for the public url so I have entered these. I've also tried https://hidriveusername.webdav.hidrive.ionos.com for the private url - same problem.
I've read another thread here and tried a whole host of other variations.
Can anyone help me please? I've also emailed IONOS but I suspect they will refer me to you.
I tried to upload a screenshot of the links going into the addon but "something went really wrong and we can't process that file"
Thanks in advance.

**Comment by darktrojan** [comment]
Same as #1. Should be fixed now pending approval on the add-ons website.
