### ISSUE TITLE
Not compatible with Thunderbird 102.0

### ISSUE THREAD

**Issue by daradib** [thunderbird/webdav-filelink#7]
Thunderbird 102.0 was released yesterday and disables the addon because it is not marked as compatible.

File linking seems to work fine when the preference `extensions.checkCompatibility.102.0` is set to false. Assuming the auth prompt works too, perhaps remove `strict_max_version` from manifest.json?

**Comment by kaspercat** [comment]
Can we have an update for this to be compatible for the latest version of Thunderbird? version 102.x?

**Comment by darktrojan** [comment]
It _is_ compatible with 102.
